/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Excepciones.*;
import Personas.AdministradorAcopio;
import Personas.Contable;
import Personas.Secretaria;
import Personas.Usuario;

/**
 *
 * @author Kevin
 */
public class LogIn extends javax.swing.JPanel {
 public Ventana parent;
    /**
     * Creates new form LogIn
     * @param parent Es el Frame de tipo ventana en el que se encuentra el Panel, sirve de puntero para los eventos.
     */
    public LogIn(Ventana parent) {
        this.parent=parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 1, 36)); // NOI18N
        jLabel1.setText("Bienvenido");

        jLabel2.setText("Carnet de identidad:");

        jTextField1.setText("jTextField1");

        jLabel3.setText("Contraseña:");

        jTextField2.setText("jTextField2");

        jButton1.setText("Iniciar Sesion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                        .addComponent(jTextField1)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jButton1))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if(jTextField1.getText().equals("")||jTextField2.getText().equals("")){
                throw new CampoDeTextoVacioExcepcion();
            }
            int CI=Integer.valueOf(jTextField1.getText());
            Usuario usuarioActual = this.parent.getEmpresa().getUserByCI(CI);
        
            if(usuarioActual.getContrasenna().equals(jTextField2.getText())){
                this.parent.setUsuario(usuarioActual);
            }else{
                throw new ContrasennaIncorectaExcepcion();
            }
            
            if(usuarioActual instanceof  AdministradorAcopio) parent.setVisualAdministrador();
            else if(usuarioActual instanceof Secretaria) parent.setVisualSecretaria();
            else if(usuarioActual instanceof Contable) parent.setVisualContable();
            else parent.setVisualTransportista();
            
        } catch (CampoDeTextoVacioExcepcion
                | UsuarioNoEncontradoExcepcion
                | ContrasennaIncorectaExcepcion ex) {
            VentanaNotificacion notificacion=new VentanaNotificacion(parent, ex.getMessage());
        } catch(NullPointerException e){
            VentanaNotificacion notificacion=new VentanaNotificacion(parent, "El CI introducido no es un numero entero.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
